/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Control DTO  object exposed to the endpoints  @attribute sampling_time: Time that takes the Control to refresh it\'s data @attribute variables: A string of the system variables used in the script, that will be transformed into a list
 */
export interface ControlfunctionDto { 
    name: string;
    units: string;
    start_time: number;
    status: number;
    script_function: string;
    sampling_time: number;
    variables: Array<any>;
}

