/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Object used to update the fields from the control that the user can modify  @attribute script_function: the function that the script will execute @attribute sampling_time: time between executions. @attribute variables: A string of the system variables used in the script, that will be transformed into a list
 */
export interface ControlfunctionFields { 
    script_function: string;
    sampling_time: number;
    variables: Array<any>;
}

