/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GasPointDTO } from './gasPointDTO';


/**
 * Profile model object  Attributes:     profile_name: profile name in BDD     units: units     script_function: script code in string format     start_time: start (ON) profile time     status: profile status (on, off, ...)     variable_list: variables involved in profile process     is_loop_active: variable that enable the loop execution     points: string in JSON format with profile points     sampling_time: time between exec.     cache_sp1: cache direction for save sp gas1 variable.     cache_sp2: cache direction for save sp gas2 variable.     cache_sp3: cache direction for save sp gas3 variable.     cache_sp4: cache direction for save sp gas4 variable.     cache_sp5: cache direction for save sp gas5 variable.
 */
export interface GasProfileDTO { 
    name: string;
    units: string;
    start_time: number;
    status: number;
    script_function: string;
    sampling_time?: number;
    variable_list?: Array<string>;
    is_loop_active?: boolean;
    points?: Array<GasPointDTO>;
    cache_sp1?: string;
    cache_sp2?: string;
    cache_sp3?: string;
    cache_sp4?: string;
    cache_sp5?: string;
}

