/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Gas profile point Attributes:     time: timestamp from initial script moment to this point.     sp1: set point for this gas1 point.     sp2: set point for this gas2 point.     sp3: set point for this gas3 point.     sp4: set point for this gas4 point.     sp5: set point for this gas5 point.
 */
export interface GasPointDTO { 
    time?: number;
    sp1?: number;
    sp2?: number;
    sp3?: number;
    sp4?: number;
    sp5?: number;
}

