/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Profile point Attributes:     time: timestamp from initial script moment to this point.     sp: set point for this point.     mu: exponential parameter.
 */
export interface PointDTO { 
    time?: number;
    sp?: number;
    mu?: number;
}

