/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 *  Represents the basic HTTP verbs      Values:         - GET: get         - POST: post         - DELETE: delete         - PUT: put     
 */
export type HTTPMethod = 'get' | 'post' | 'delete' | 'put';

export const HTTPMethod = {
    Get: 'get' as HTTPMethod,
    Post: 'post' as HTTPMethod,
    Delete: 'delete' as HTTPMethod,
    Put: 'put' as HTTPMethod
};

