/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a user object of Keycloak.  Attributes:     id (str):     createdTimestamp (int):     username (str):     enabled (bool):     totp (bool):     emailVerified (bool):     firstName (Optional[str]):     lastName (Optional[str]):     email (Optional[str]):     disableableCredentialTypes (List[str]):     requiredActions (List[str]):     realmRoles (List[str]):     notBefore (int):     access (dict):     attributes (Optional[dict]):  Notes: Check the Keycloak documentation at https://www.keycloak.org/docs-api/15.0/rest-api/index.html for details. This is a mere proxy object.
 */
export interface KeycloakUser { 
    id: string;
    createdTimestamp: number;
    username: string;
    enabled: boolean;
    totp: boolean;
    emailVerified: boolean;
    firstName?: string;
    lastName?: string;
    email?: string;
    disableableCredentialTypes: Array<string>;
    requiredActions: Array<string>;
    realmRoles?: Array<string>;
    notBefore: number;
    access: object;
    attributes?: object;
}

